language: node_js

os:
  - linux
  - osx

cache:
  bundler: true

node_js:
- 8
- node

script:
  - npm run lint
  - npm run test

after_script:
  - npm webpack --mode production
  - npm pack
  - VXPAY_JS_VER=$(node -p "require('./package.json').version")
  - mkdir vxpay-js-app && cd vxpay-js-app
  - npm install "../vxpay-js-$VXPAY_JS_VER.tgz"
  - ls -l node_modules/vxpay-js/
