language: node_js

os:
  - linux
  - osx

cache:
  bundler: true

node_js:
- 8
- node

script:
  - npm run lint
  - npm run test

after_script:
  # build the package
  - npm webpack --mode production
  - npm pack
  - mkdir vxpay-js-app && cd vxpay-js-app
  - npm install "../vxpay-js-$(node -p "require('./package.json').version").tgz"
  - ls -l node_modules/vxpay-js/
