language: node_js

os:
- linux
- osx

cache:
  - bundler
  - npm

# test step is auto-configured: npm run test

stages:
  - lint
  - test
  - build
  - deploy
  - coverage

node_js:
- 8
- node

jobs:
  include:

  - stage: lint
    name: "ESLint"
    script: npm run lint

  - stage: build
    name: "Build, pack & confirm NPM package"
    script:
    - npm run build
    - npm run copy
    - cp -R build/. dist/ # copy the build files to folder that is not ignored
    - npm pack
    - VXPAY_JS_VER=$(node -p "require('./package.json').version")
    - echo "$VXPAY_JS_VER"
    - cd ../
    - mkdir vxpay-js-integration
    - cd vxpay-js-integration
    - npm install "../vxpay-js/vxpay-js-$VXPAY_JS_VER.tgz"
    - ls -l node_modules/vxpay-js/dist/

  - stage: deploy
    name: "Release NPM package on TAG"
    script:
      - echo "Deploying to npm ..."
      - npm run build
      - cp -R build/. dist/ # copy the build files to folder that is not ignored
    deploy:
      skip_cleanup: true
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$API_KEY"
      on:
        tags: true

  - stage: coverage
    name: "Submit coverage to Coveralls"
    if: branch = master # on master only
    script:
      - npm run coveralls
