language: node_js

os:
  - linux
  - osx

cache:
  bundler: true

node_js:
- 8
- node

script:
  - npm run lint
  - npm run test
  # build, pack and install
  - ./node_modules/.bin/webpack --mode production
  - npm pack
  - VXPAY_JS_VER=$(node -p "require('./package.json').version")
  - echo "$VXPAY_JS_VER"
  - cd ../
  - mkdir vxpay-js-integration
  - cd vxpay-js-integration
  - npm install "../vxpay-js/vxpay-js-$VXPAY_JS_VER.tgz"
  - ls -l node_modules/vxpay-js/

#deploy:
#  provider: npm
#  email: "$NPM_EMAIL"
#  api_key: "$API_KEY"
#  on:
#    tags: true
