language: node_js

os:
- linux
- osx

cache:
  bundler: true

# test step is auto-configured: npm run test

stages:
  - lint
  - test
  - build
  - deploy

node_js:
- 8
- node

jobs:
  include:

  - stage: lint
    name: "ESLint"
    string:
     - npm run lint
     - npm run cover

  - stage: build
    name: "Build, pack & confirm NPM package"
    script:
    - npm run build
    - npm run copy
    # copy the build files to folder that is not ignored
    - cp -R build/. dist/
    - npm pack
    - VXPAY_JS_VER=$(node -p "require('./package.json').version")
    - echo "$VXPAY_JS_VER"
    - cd ../
    - mkdir vxpay-js-integration
    - cd vxpay-js-integration
    - npm install "../vxpay-js/vxpay-js-$VXPAY_JS_VER.tgz"
    - ls -l node_modules/vxpay-js/dist/

  - stage: deploy
    name: "Release NPM package on TAG"
    script: echo "Deploying to npm ..."
    before_deploy:
      # copy the build files to folder that is not ignored
      - cp -R build/. dist/
    deploy:
      skip_cleanup: true
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$API_KEY"
      on:
        tags: true
