language: node_js

os:
  - linux
  - osx

cache:
  directories:
  - node_modules

node_js:
- 8
- node

after_script:
  - echo "Try to pack the lib for npm ..."
  - npm pack
  - echo "Try to install packed archive ..."
  - NPM_PACK_VER="$(node -p "require('./package.json').version")"
  - mkdir vxpay-js-app
  - cd vxpay-js-app
  - echo "../vxpay-js-$NPM_PACK_VER.tgz"
